import React from 'react'

const Footer = () => {
  return (
    <div className='p-3 flex justify-center items-center'>
        <p>© Generated by Insomniac</p>
    </div>

  )
}

export default Footer